### ISSUE TITLE
Pusing a modulemd with only digits in the context field fails

### ISSUE THREAD

**Issue by bstinsonmhk** [release-engineering/alt-src#31]
We're trying to push `go-toolset-rhel8-8030020200626181103.1370236` for CentOS Stream, but when we try to do so we get a traceback:
```2020-07-13 20:16:46,129 [ERROR] Staging failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/alt_src/alt_src.py", line 2082, in main
    task.run()
  File "/usr/lib/python2.7/site-packages/alt_src/alt_src.py", line 646, in run
    self.read_source_file()
  File "/usr/lib/python2.7/site-packages/alt_src/alt_src.py", line 312, in read_source_file
    self.read_mmd()
  File "/usr/lib/python2.7/site-packages/alt_src/alt_src.py", line 327, in read_mmd
    release = '.'.join((str(module_data['version']), module_data['context']))
TypeError: sequence item 1: expected string, int found
```

We're using `python-alt-src-1.0.0-1.el7eng.noarch` so the traceback should correspond to this line:

https://github.com/release-engineering/alt-src/blob/bccdea92c2a433ae04531e7e4f60ce261be2b790/alt_src/alt_src.py#L330

**Comment by rbikar** [comment]
@bstinsonmhk 
This was already fixed in https://github.com/release-engineering/alt-src/pull/14 and released in https://pypi.org/project/alt-src/1.1.0/ 
I would recommend to update to the latest available version which is 1.3.0, also it is available as internal rpm -> python-alt-src-1.3.0-1.el7eng . I'll close this now.
